apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
spec: 
  type: NodePort
  selector:
    role: api
  ports:
  - port: 3500
    targetPort: 3500
    nodePort: 31500
    protocol: TCP