apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: aayusharma1410/3-tier-frontend:v1
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://192.168.49.2:31500/api/tasks"
        ports:
        - containerPort: 3000